name: Build and Upload to JFrog

on:
  workflow_call:
    secrets:
      JFROG_URL:
        required: true
      JFROG_TOKEN:
        required: true
      JFROG_REPO:
        required: true

jobs:
  build:
    name: Build and Upload to JFrog
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Application
        run: mvn clean install -DskipTests

      - name: Configure JFrog
        run: |
          jfrog config add my-server \
            --url="${{ secrets.JFROG_URL }}" \
            --access-token="${{ secrets.JFROG_TOKEN }}" \
            --interactive=false

      - name: Upload Artifact to JFrog
        run: |
          jfrog rt u "target/*.jar" "${{ secrets.JFROG_REPO }}" --flat=false
